### ISSUE TITLE
nuget install support?

### ISSUE THREAD

**Issue by dirkraft** [bitcraftCoLtd/protobuf3-for-unity#2]
Is there a way to nuget install this? I'm new to C#, .NET, and adding libraries into my project so my question might not even make sense. I am developing on a Mac, so am testing the full extent of limitations of Unity's Mono, particularly that it most resembles .NET 3.5 (from what I understand).

I was able to `nuget install protobuf3 -Pre` (https://github.com/emikra/protobuf3-cs) to my **Unity project**, but it is based on protobuf v3.0.0-beta-2 and I need beta-3 for some reasons of convenience. This repo seems to represent that.

**Comment by TanukiSharp** [comment]
Hello dirkraft

We do not provide NuGet packages, since those make few sense with Unity, unfortunately.

What I may advice you is to checkout the `v3.0.0-beta-3` branch here https://github.com/bitcraftCoLtd/protobuf3-for-unity/tree/v3.0.0-beta-3 then build it, and eventually drop the produced .dll file in the `Asssets/Plugins` folder of your Unity project.

I hope this help.

**Comment by dirkraft** [comment]
Sometimes the nuget packages seem to work with unity (I'm using some version of LibNoise from there). There are some problems building protobuf c# on mono. I'll have to try to figure that out, but it's not specifically a problem with this project. Thanks for the reply and advice.

**Comment by qbrandon** [comment]
For the record, there is now a release archive so that you no longer have to build the source yourself:
https://github.com/bitcraftCoLtd/protobuf3-for-unity/releases
