### ISSUE TITLE
Can this assembly be used cross platform?

### ISSUE THREAD

**Issue by jswigart** [bitcraftCoLtd/protobuf3-for-unity#3]
It sounds like this is windows only? Does that mean you can't use it on the many other platforms that unity can target? Or is that just for compilation of it?

**Comment by hobein** [comment]
You can use this repository to compile the dll that target unity .net 3.5

If you want to use the dll directly, you can download the release [here](https://github.com/bitcraftCoLtd/protobuf3-for-unity/releases/tag/v3.0.0_beta_3)

The DLL is not platform-specific.

I hope this help.

**Comment by jswigart** [comment]
When using in unity, do we use the regular protoc.exe compiler that protobuf 3 uses to generate code from the .proto files? Do we need any custom protoc.exe version?

**Comment by HelloKitty** [comment]
Haven't used this project yet but protoc should generate classes that are build utilizing proto3 spec and with types available in Google.Protobuf's proto3 C# implementation.

This is merely a net35 port that rips out net40/net45 stuff and replaces it with comparable things. The general API and Types are intact, I would hope, so the newer version of protoc will be needed especially since older protoc versions cannot read proto3.

**Comment by qbrandon** [comment]
Closing this issue since there appear to be no more question.
